---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
- name: selfhydro-ui
- name: version

outputs:
- name: selfhydro-ui-build

run:
  path: selfhydro-ui/.ci/build.sh
